apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: stack-microservices
  annotations:
    meta.crossplane.io/maintainer: Patrick Lee Scott
    meta.crossplane.io/source: github.com/hops-ops/stack-microservices
    meta.crossplane.io/description: Microservices stack composing Istio, Knative Operator, Knative Serving/Eventing, and optional NATS.
spec:
  dependsOn:
  - function: xpkg.crossplane.io/crossplane-contrib/function-auto-ready
    version: ">=v0.6.0"
  - configuration: ghcr.io/hops-ops/helm-istiod
    version: ">=v0.1.0"
  - configuration: ghcr.io/hops-ops/helm-knative-operator
    version: ">=v0.1.0"
  - configuration: ghcr.io/hops-ops/helm-nats
    version: ">=v0.1.0"
  - provider: xpkg.crossplane.io/crossplane-contrib/provider-kubernetes
    version: ">=v1.2.0"
